---
info:
  component: Centralized Swagger Documentation for MicroServices

spring:
  profiles: default

documentation:
  baseurl: http://localhost
  swagger:
    services:
      - name: Crud
        url: ${documentation.baseurl}:8888/v2/api-docs
        version: 1.0
      - name: Service 2
        url: ${documentation.baseurl}:8083/v2/api-docs
        version: 1.0